INSERT IGNORE INTO `rex_iwcc_text` (`pid`, `id`, `clang_id`, `uid`, `text`) VALUES
(1, 1, 1, 'headline', 'Cookie-Verwaltung'),
(2, 2, 1, 'description', 'Wir verwenden Cookies, um Ihnen ein optimales Webseiten-Erlebnis zu bieten. Dazu zählen Cookies, die für den Betrieb der Seite und für die Steuerung unserer kommerziellen Unternehmensziele notwendig sind, sowie solche, die lediglich zu anonymen Statistikzwecken, für Komforteinstellungen oder zur Anzeige personalisierter Inhalte genutzt werden. Sie können selbst entscheiden, welche Kategorien Sie zulassen möchten. Bitte beachten Sie, dass auf Basis Ihrer Einstellungen womöglich nicht mehr alle Funktionalitäten der Seite zur Verfügung stehen.'),
(3, 3, 1, 'toggle_details', 'Details anzeigen/ausblenden'),
(4, 4, 1, 'provider', 'Anbieter:'),
(5, 5, 1, 'link_privacy', 'Datenschutzerklärung'),
(6, 6, 1, 'lifetime', 'Laufzeit:'),
(7, 7, 1, 'button_accept', 'Auswahl bestätigen'),
(8, 8, 1, 'button_select_all', 'Alle auswählen'),
(9, 9, 1, 'cookiename', 'Cookie-Name:'),
(10, 10, 1, 'usage', 'Service:'),
(11, 11, 1, 'usage', 'Verwendungszweck:'),
(12, 12, 1, 'category', 'Kategorie:'),
(13, 13, 1, 'value', 'Wert:'),
(14, 14, 1, 'missingdescription', 'Keine Informationen vorhanden');