package: consent_manager
version: "4.5.4"
author: "Friends Of REDAXO"
supportpage: https://redaxo.org/support/community/#slack

page:
  title: "translate:consent_manager_title"
  perm: consent_manager[]
  pjax: true
  icon: rex-icon fa fa-coffee
  subpages:
    config:
      title: "Settings"
      icon: rex-icon fa-cog
    cookiegroup:
      title: "translate:consent_manager_cookiegroups"
    cookie:
      title: "translate:consent_manager_cookies"
    text:
      title: "translate:consent_manager_texts"
    domain:
      title: "translate:consent_manager_domains"
    theme:
      title: "translate:consent_manager_theme"
    theme_editor:
      title: "Theme Editor"
      icon: rex-icon fa-paint-brush
    log:
      title: "translate:consent_manager_log"
    help:
      {
        title: "translate:consent_manager_help",
        icon: rex-icon fa-question-circle,
        subPath: README.md,
        itemClass: pull-right,
      }
    inline:
      {
        title: "Inline Consent",
        icon: rex-icon fa-play-circle,
        subPath: inline.md,
        itemClass: pull-right,
      }
    changelog:
      {
        title: "translate:consent_manager_changelog",
        subPath: CHANGELOG.md,
        itemClass: pull-right,
      }

requires:
  redaxo: "^5.12"
  php:
    version: ">=7, <9"

default_config:
  hidebodyscrollbar: false
  outputowncss: false
  skip_consent: ''
  lifespan: 365
  theme: false
  first_run_completed: false

installer_ignore:
    - .github
    - .gitignore

console_commands:
    consent_manager:log-delete: FriendsOfRedaxo\ConsentManager\Command\LogDelete
