package: iwcc
version: '2.0.0-beta8'
author: 'Friends Of REDAXO'
supportpage: https://redaxo.org/support/community/#slack

requires:
    redaxo: '^5.8'

page:
    title: 'translate:iwcc_title'
    perm: iw_cookie_consent[]
    pjax: true
    icon: rex-icon fa fa-coffee
    subpages:
        cookiegroup:
            title: 'translate:iwcc_cookiegroups'
        cookie:
            title: 'translate:iwcc_cookies'
        text:
            title: 'translate:iwcc_texts'
        domain:
            title: 'translate:iwcc_domains'
        setup:
            title: 'translate:iwcc_setup'
        help:
            {title: 'translate:iwcc_help',  icon: rex-icon fa-question-circle, subPath: README.md, itemclass: pull-right}
