package: consent_manager
version: "4.4.3"
author: "Friends Of REDAXO"
supportpage: https://redaxo.org/support/community/#slack

page:
  title: "translate:consent_manager_title"
  perm: consent_manager[]
  pjax: true
  icon: rex-icon fa fa-coffee
  subpages:
    config:
      title: "Settings"
      icon: rex-icon fa-cog
    cookiegroup:
      title: "translate:consent_manager_cookiegroups"
    cookie:
      title: "translate:consent_manager_cookies"
    text:
      title: "translate:consent_manager_texts"
    domain:
      title: "translate:consent_manager_domains"
    theme:
      title: "translate:consent_manager_theme"
    log:
      title: "translate:consent_manager_log"
    help:
      {
        title: "translate:consent_manager_help",
        icon: rex-icon fa-question-circle,
        subPath: README.md,
        itemClass: pull-right,
      }
    changelog:
      {
        title: "translate:consent_manager_changelog",
        subPath: CHANGELOG.md,
        itemClass: pull-right,
      }

requires:
  redaxo: "^5.12"
  php:
    version: ">=7, <9"

default_config:
  hidebodyscrollbar: false
  outputowncss: false
  skip_consent: ''
  lifespan: 365
  theme: false
  first_run_completed: false

installer_ignore:
    - .github
    - .gitignore
