package: consent_manager
version: "5.3.4"
author: "Friends Of REDAXO"
supportpage: https://redaxo.org/support/community/#slack

page:
  title: "translate:consent_manager_title"
  perm: consent_manager[]
  pjax: true
  icon: rex-icon fa-solid fa-cookie-bite
  subpages:
    config:
      title: "Settings"
      icon: rex-icon fa-cog
      perm: consent_manager[config]
    editorial:
      title: "translate:consent_manager_editorial_title"
      icon: rex-icon fa-edit
      perm: consent_manager[editorial]
    cookiegroup:
      title: "translate:consent_manager_cookiegroups"
      icon: rex-icon fa-folder-open
      perm: consent_manager[config]
    cookie:
      title: "translate:consent_manager_cookies"
      icon: rex-icon fa-cog
      perm: consent_manager[config]
    text:
      title: "translate:consent_manager_texts"
      icon: rex-icon fa-file-text-o
      perm: consent_manager[config]
    domain:
      title: "translate:consent_manager_domains"
      icon: rex-icon fa-globe
      perm: consent_manager[config]
    theme:
      title: "translate:consent_manager_theme"
      icon: rex-icon fa-grip
      perm: consent_manager[config]
    theme_editor:
      title: "Theme Editor"
      icon: rex-icon fa-magic
      perm: consent_manager[config]
    log:
      title: "translate:consent_manager_log"
    help:
      title: "translate:consent_manager_help"
      icon: rex-icon fa-info


requires:
  redaxo: "^5.15"
  php:
    version: ">=8.1, <9"

default_config:
  hidebodyscrollbar: false
  outputowncss: false
  skip_consent: ''
  cookie_name: 'consentmanager'
  lifespan: 365
  theme: false
  first_run_completed: false

installer_ignore:
    - .github
    - .gitignore
    - .semgrep
    # development and test artifacts — should not be included in the released zip
    - node_modules
    - assets/tests
    - tests
    - phpunit.xml
    - .php_cs
    - .php_cs.dist
    - .php-cs-fixer.php
    - .php-cs-fixer.dist.php
    - .php-cs-fixer
    - .php_cs.cache
    - .php-cs-fixer.cache
    - composer.phar
    - composer.json
    - composer.lock
    - package.json
    - package-lock.json
    - playwright.config.js
    - test-results
    - vendor
    - .github/workflows

console_commands:
    consent_manager:log-delete: FriendsOfRedaxo\ConsentManager\Command\LogDelete
